//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PumpHouse.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DWC_Service")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Email {
            get {
                return this.User_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.User_EmailField, value) != true)) {
                    this.User_EmailField = value;
                    this.RaisePropertyChanged("User_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Name {
            get {
                return this.User_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_NameField, value) != true)) {
                    this.User_NameField = value;
                    this.RaisePropertyChanged("User_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Password {
            get {
                return this.User_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PasswordField, value) != true)) {
                    this.User_PasswordField = value;
                    this.RaisePropertyChanged("User_Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_PhoneNo {
            get {
                return this.User_PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PhoneNoField, value) != true)) {
                    this.User_PhoneNoField = value;
                    this.RaisePropertyChanged("User_PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Surname {
            get {
                return this.User_SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_SurnameField, value) != true)) {
                    this.User_SurnameField = value;
                    this.RaisePropertyChanged("User_Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Type {
            get {
                return this.User_TypeField;
            }
            set {
                if ((this.User_TypeField.Equals(value) != true)) {
                    this.User_TypeField = value;
                    this.RaisePropertyChanged("User_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/DWC_Service")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_StreetName_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_SuburbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.Invoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.ShoppingCart[] ShoppingCartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_PostCode {
            get {
                return this.Customer_PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_PostCodeField, value) != true)) {
                    this.Customer_PostCodeField = value;
                    this.RaisePropertyChanged("Customer_PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_Province {
            get {
                return this.Customer_ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_ProvinceField, value) != true)) {
                    this.Customer_ProvinceField = value;
                    this.RaisePropertyChanged("Customer_Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_StreetName_No {
            get {
                return this.Customer_StreetName_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_StreetName_NoField, value) != true)) {
                    this.Customer_StreetName_NoField = value;
                    this.RaisePropertyChanged("Customer_StreetName_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_Suburb {
            get {
                return this.Customer_SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_SuburbField, value) != true)) {
                    this.Customer_SuburbField = value;
                    this.RaisePropertyChanged("Customer_Suburb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.Invoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.ShoppingCart[] ShoppingCarts {
            get {
                return this.ShoppingCartsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartsField, value) != true)) {
                    this.ShoppingCartsField = value;
                    this.RaisePropertyChanged("ShoppingCarts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/DWC_Service")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cart_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Invioce_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Invioce_TotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoice_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Invoice_TAXNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.ShoppingCart ShoppingCartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cart_Id {
            get {
                return this.Cart_IdField;
            }
            set {
                if ((this.Cart_IdField.Equals(value) != true)) {
                    this.Cart_IdField = value;
                    this.RaisePropertyChanged("Cart_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Invioce_Date {
            get {
                return this.Invioce_DateField;
            }
            set {
                if ((this.Invioce_DateField.Equals(value) != true)) {
                    this.Invioce_DateField = value;
                    this.RaisePropertyChanged("Invioce_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Invioce_TotalAmount {
            get {
                return this.Invioce_TotalAmountField;
            }
            set {
                if ((this.Invioce_TotalAmountField.Equals(value) != true)) {
                    this.Invioce_TotalAmountField = value;
                    this.RaisePropertyChanged("Invioce_TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoice_No {
            get {
                return this.Invoice_NoField;
            }
            set {
                if ((this.Invoice_NoField.Equals(value) != true)) {
                    this.Invoice_NoField = value;
                    this.RaisePropertyChanged("Invoice_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invoice_TAXNo {
            get {
                return this.Invoice_TAXNoField;
            }
            set {
                if ((object.ReferenceEquals(this.Invoice_TAXNoField, value) != true)) {
                    this.Invoice_TAXNoField = value;
                    this.RaisePropertyChanged("Invoice_TAXNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.ShoppingCart ShoppingCart {
            get {
                return this.ShoppingCartField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartField, value) != true)) {
                    this.ShoppingCartField = value;
                    this.RaisePropertyChanged("ShoppingCart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCart", Namespace="http://schemas.datacontract.org/2004/07/DWC_Service")]
    [System.SerializableAttribute()]
    public partial class ShoppingCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cart_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Cart_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Cart_TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.Invoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.ShoppingCartBridge[] ShoppingCartBridgesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USER_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cart_ID {
            get {
                return this.Cart_IDField;
            }
            set {
                if ((this.Cart_IDField.Equals(value) != true)) {
                    this.Cart_IDField = value;
                    this.RaisePropertyChanged("Cart_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cart_Status {
            get {
                return this.Cart_StatusField;
            }
            set {
                if ((this.Cart_StatusField.Equals(value) != true)) {
                    this.Cart_StatusField = value;
                    this.RaisePropertyChanged("Cart_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cart_Total {
            get {
                return this.Cart_TotalField;
            }
            set {
                if ((this.Cart_TotalField.Equals(value) != true)) {
                    this.Cart_TotalField = value;
                    this.RaisePropertyChanged("Cart_Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.Invoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.ShoppingCartBridge[] ShoppingCartBridges {
            get {
                return this.ShoppingCartBridgesField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartBridgesField, value) != true)) {
                    this.ShoppingCartBridgesField = value;
                    this.RaisePropertyChanged("ShoppingCartBridges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USER_Id {
            get {
                return this.USER_IdField;
            }
            set {
                if ((this.USER_IdField.Equals(value) != true)) {
                    this.USER_IdField = value;
                    this.RaisePropertyChanged("USER_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartBridge", Namespace="http://schemas.datacontract.org/2004/07/DWC_Service")]
    [System.SerializableAttribute()]
    public partial class ShoppingCartBridge : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Bridge_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Bridge_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cart_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.ShoppingCart ShoppingCartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bridge_Id {
            get {
                return this.Bridge_IdField;
            }
            set {
                if ((this.Bridge_IdField.Equals(value) != true)) {
                    this.Bridge_IdField = value;
                    this.RaisePropertyChanged("Bridge_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bridge_Quantity {
            get {
                return this.Bridge_QuantityField;
            }
            set {
                if ((this.Bridge_QuantityField.Equals(value) != true)) {
                    this.Bridge_QuantityField = value;
                    this.RaisePropertyChanged("Bridge_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cart_ID {
            get {
                return this.Cart_IDField;
            }
            set {
                if ((this.Cart_IDField.Equals(value) != true)) {
                    this.Cart_IDField = value;
                    this.RaisePropertyChanged("Cart_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_ID {
            get {
                return this.Product_IDField;
            }
            set {
                if ((this.Product_IDField.Equals(value) != true)) {
                    this.Product_IDField = value;
                    this.RaisePropertyChanged("Product_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.ShoppingCart ShoppingCart {
            get {
                return this.ShoppingCartField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartField, value) != true)) {
                    this.ShoppingCartField = value;
                    this.RaisePropertyChanged("ShoppingCart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/DWC_Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Product_AvailabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Product_DiscountAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Product_DiscountStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Product_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PumpHouse.ServiceReference1.ShoppingCartBridge[] ShoppingCartBridgesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Product_Availability {
            get {
                return this.Product_AvailabilityField;
            }
            set {
                if ((this.Product_AvailabilityField.Equals(value) != true)) {
                    this.Product_AvailabilityField = value;
                    this.RaisePropertyChanged("Product_Availability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Category {
            get {
                return this.Product_CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_CategoryField, value) != true)) {
                    this.Product_CategoryField = value;
                    this.RaisePropertyChanged("Product_Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Description {
            get {
                return this.Product_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_DescriptionField, value) != true)) {
                    this.Product_DescriptionField = value;
                    this.RaisePropertyChanged("Product_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Product_DiscountAmount {
            get {
                return this.Product_DiscountAmountField;
            }
            set {
                if ((this.Product_DiscountAmountField.Equals(value) != true)) {
                    this.Product_DiscountAmountField = value;
                    this.RaisePropertyChanged("Product_DiscountAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Product_DiscountStatus {
            get {
                return this.Product_DiscountStatusField;
            }
            set {
                if ((this.Product_DiscountStatusField.Equals(value) != true)) {
                    this.Product_DiscountStatusField = value;
                    this.RaisePropertyChanged("Product_DiscountStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_Id {
            get {
                return this.Product_IdField;
            }
            set {
                if ((this.Product_IdField.Equals(value) != true)) {
                    this.Product_IdField = value;
                    this.RaisePropertyChanged("Product_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Image {
            get {
                return this.Product_ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_ImageField, value) != true)) {
                    this.Product_ImageField = value;
                    this.RaisePropertyChanged("Product_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Name {
            get {
                return this.Product_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_NameField, value) != true)) {
                    this.Product_NameField = value;
                    this.RaisePropertyChanged("Product_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Product_Price {
            get {
                return this.Product_PriceField;
            }
            set {
                if ((this.Product_PriceField.Equals(value) != true)) {
                    this.Product_PriceField = value;
                    this.RaisePropertyChanged("Product_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_Quantity {
            get {
                return this.Product_QuantityField;
            }
            set {
                if ((this.Product_QuantityField.Equals(value) != true)) {
                    this.Product_QuantityField = value;
                    this.RaisePropertyChanged("Product_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PumpHouse.ServiceReference1.ShoppingCartBridge[] ShoppingCartBridges {
            get {
                return this.ShoppingCartBridgesField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartBridgesField, value) != true)) {
                    this.ShoppingCartBridgesField = value;
                    this.RaisePropertyChanged("ShoppingCartBridges");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        PumpHouse.ServiceReference1.User GetUser(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        System.Threading.Tasks.Task<PumpHouse.ServiceReference1.User> GetUserAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserRegistration", ReplyAction="http://tempuri.org/IService1/UserRegistrationResponse")]
        int UserRegistration(string name, string surname, string email, string phoneno, string password, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserRegistration", ReplyAction="http://tempuri.org/IService1/UserRegistrationResponse")]
        System.Threading.Tasks.Task<int> UserRegistrationAsync(string name, string surname, string email, string phoneno, string password, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        int UserLogin(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogin", ReplyAction="http://tempuri.org/IService1/UserLoginResponse")]
        System.Threading.Tasks.Task<int> UserLoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserType", ReplyAction="http://tempuri.org/IService1/getUserTypeResponse")]
        int getUserType(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserType", ReplyAction="http://tempuri.org/IService1/getUserTypeResponse")]
        System.Threading.Tasks.Task<int> getUserTypeAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditUser", ReplyAction="http://tempuri.org/IService1/EditUserResponse")]
        bool EditUser(int UsersId, int Id, string Name, string Surname, string Email, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditUser", ReplyAction="http://tempuri.org/IService1/EditUserResponse")]
        System.Threading.Tasks.Task<bool> EditUserAsync(int UsersId, int Id, string Name, string Surname, string Email, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduct", ReplyAction="http://tempuri.org/IService1/GetProductResponse")]
        PumpHouse.ServiceReference1.Product GetProduct(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduct", ReplyAction="http://tempuri.org/IService1/GetProductResponse")]
        System.Threading.Tasks.Task<PumpHouse.ServiceReference1.Product> GetProductAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProducts", ReplyAction="http://tempuri.org/IService1/getAllProductsResponse")]
        PumpHouse.ServiceReference1.Product[] getAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProducts", ReplyAction="http://tempuri.org/IService1/getAllProductsResponse")]
        System.Threading.Tasks.Task<PumpHouse.ServiceReference1.Product[]> getAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        void AddProduct(int UsersId, string name, string category, string description, decimal price, int quantity, bool discountstatus, decimal discountamount, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        System.Threading.Tasks.Task AddProductAsync(int UsersId, string name, string category, string description, decimal price, int quantity, bool discountstatus, decimal discountamount, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        bool DeleteProduct(int UsersId, string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(int UsersId, string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditProduct", ReplyAction="http://tempuri.org/IService1/EditProductResponse")]
        bool EditProduct(int UsersId, int Id, string Name, string Description, decimal Price, int quantity, bool discountstatus, decimal discountamount, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditProduct", ReplyAction="http://tempuri.org/IService1/EditProductResponse")]
        System.Threading.Tasks.Task<bool> EditProductAsync(int UsersId, int Id, string Name, string Description, decimal Price, int quantity, bool discountstatus, decimal discountamount, string image);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PumpHouse.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PumpHouse.ServiceReference1.IService1>, PumpHouse.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PumpHouse.ServiceReference1.User GetUser(int Id) {
            return base.Channel.GetUser(Id);
        }
        
        public System.Threading.Tasks.Task<PumpHouse.ServiceReference1.User> GetUserAsync(int Id) {
            return base.Channel.GetUserAsync(Id);
        }
        
        public int UserRegistration(string name, string surname, string email, string phoneno, string password, int type) {
            return base.Channel.UserRegistration(name, surname, email, phoneno, password, type);
        }
        
        public System.Threading.Tasks.Task<int> UserRegistrationAsync(string name, string surname, string email, string phoneno, string password, int type) {
            return base.Channel.UserRegistrationAsync(name, surname, email, phoneno, password, type);
        }
        
        public int UserLogin(string email, string password) {
            return base.Channel.UserLogin(email, password);
        }
        
        public System.Threading.Tasks.Task<int> UserLoginAsync(string email, string password) {
            return base.Channel.UserLoginAsync(email, password);
        }
        
        public int getUserType(int Id) {
            return base.Channel.getUserType(Id);
        }
        
        public System.Threading.Tasks.Task<int> getUserTypeAsync(int Id) {
            return base.Channel.getUserTypeAsync(Id);
        }
        
        public bool EditUser(int UsersId, int Id, string Name, string Surname, string Email, string Phone) {
            return base.Channel.EditUser(UsersId, Id, Name, Surname, Email, Phone);
        }
        
        public System.Threading.Tasks.Task<bool> EditUserAsync(int UsersId, int Id, string Name, string Surname, string Email, string Phone) {
            return base.Channel.EditUserAsync(UsersId, Id, Name, Surname, Email, Phone);
        }
        
        public PumpHouse.ServiceReference1.Product GetProduct(int Id) {
            return base.Channel.GetProduct(Id);
        }
        
        public System.Threading.Tasks.Task<PumpHouse.ServiceReference1.Product> GetProductAsync(int Id) {
            return base.Channel.GetProductAsync(Id);
        }
        
        public PumpHouse.ServiceReference1.Product[] getAllProducts() {
            return base.Channel.getAllProducts();
        }
        
        public System.Threading.Tasks.Task<PumpHouse.ServiceReference1.Product[]> getAllProductsAsync() {
            return base.Channel.getAllProductsAsync();
        }
        
        public void AddProduct(int UsersId, string name, string category, string description, decimal price, int quantity, bool discountstatus, decimal discountamount, string image) {
            base.Channel.AddProduct(UsersId, name, category, description, price, quantity, discountstatus, discountamount, image);
        }
        
        public System.Threading.Tasks.Task AddProductAsync(int UsersId, string name, string category, string description, decimal price, int quantity, bool discountstatus, decimal discountamount, string image) {
            return base.Channel.AddProductAsync(UsersId, name, category, description, price, quantity, discountstatus, discountamount, image);
        }
        
        public bool DeleteProduct(int UsersId, string Id) {
            return base.Channel.DeleteProduct(UsersId, Id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(int UsersId, string Id) {
            return base.Channel.DeleteProductAsync(UsersId, Id);
        }
        
        public bool EditProduct(int UsersId, int Id, string Name, string Description, decimal Price, int quantity, bool discountstatus, decimal discountamount, string image) {
            return base.Channel.EditProduct(UsersId, Id, Name, Description, Price, quantity, discountstatus, discountamount, image);
        }
        
        public System.Threading.Tasks.Task<bool> EditProductAsync(int UsersId, int Id, string Name, string Description, decimal Price, int quantity, bool discountstatus, decimal discountamount, string image) {
            return base.Channel.EditProductAsync(UsersId, Id, Name, Description, Price, quantity, discountstatus, discountamount, image);
        }
    }
}
